# ruff: noqa
"""add tables

Revision ID: 5fdae000458c
Revises:
Create Date: 2026-08-02 14:56:50.731348

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5fdae000458c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(sa.text("create extension if not exists pgcrypto"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_audit_events",
        sa.Column(
            "audit_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("admin_user_id", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("before_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_table(
        "analytics_events",
        sa.Column(
            "analytics_event_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("event_name", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("subject_id", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("analytics_event_id"),
    )
    op.create_table(
        "audience_tag_types",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tag_key", sa.Text(), nullable=False),
        sa.Column("display_name_uz", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'approved'"), nullable=False),
        sa.Column("usage_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "channel_assignment_audit",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("previous_account_key", sa.Text(), nullable=True),
        sa.Column("new_account_key", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "content_channel_posts",
        sa.Column(
            "post_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("post_kind", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("publisher_message_id", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_reason", sa.Text(), nullable=True),
        sa.Column(
            "schedule_timezone",
            sa.Text(),
            server_default=sa.text("'Asia/Tashkent'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("post_id"),
    )
    op.create_table(
        "feature_flag_audit_events",
        sa.Column(
            "audit_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("flag_name", sa.Text(), nullable=False),
        sa.Column("previous_enabled", sa.Boolean(), nullable=False),
        sa.Column("new_enabled", sa.Boolean(), nullable=False),
        sa.Column("previous_version", sa.Integer(), nullable=False),
        sa.Column("new_version", sa.Integer(), nullable=False),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_index(
        "ix_feature_flag_audit_events_flag_name_occurred_at",
        "feature_flag_audit_events",
        ["flag_name", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "feature_flag_states",
        sa.Column("flag_name", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("flag_name"),
    )
    op.create_table(
        "listener_accounts",
        sa.Column("account_key", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("health_status", sa.Text(), server_default=sa.text("'online'"), nullable=False),
        sa.Column("last_successful_event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("flood_wait_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("account_key"),
    )
    op.create_table(
        "parsing_logs",
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("correlation_id", sa.Text(), nullable=False),
        sa.Column("canonical", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "media",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "attempts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("error_type", sa.Text(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column(
            "post_ai_published", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("idempotency_key"),
    )
    op.create_table(
        "processing_jobs",
        sa.Column("job_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("queue_name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("correlation_id", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_table(
        "technical_metric_events",
        sa.Column(
            "technical_metric_event_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("metric_name", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("value", sa.Float(), server_default=sa.text("1"), nullable=False),
        sa.Column("component", sa.Text(), nullable=True),
        sa.Column("subject_id", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("technical_metric_event_id"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_username", sa.Text(), nullable=True),
        sa.Column("referral_code", sa.Text(), nullable=False),
        sa.Column("referred_by", sa.BigInteger(), nullable=True),
        sa.Column("premium_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "active_referral_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["referred_by"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "ingestion_sources",
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("source_type", sa.Text(), nullable=False),
        sa.Column("identifier", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("adapter_name", sa.Text(), nullable=True),
        sa.Column("listener_account_key", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("average_response_ms", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listener_account_key"],
            ["listener_accounts.account_key"],
        ),
        sa.PrimaryKeyConstraint("source_id"),
    )
    op.create_table(
        "referral_audit_events",
        sa.Column(
            "audit_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_table(
        "referral_events",
        sa.Column(
            "referral_event_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("referrer_user_id", sa.BigInteger(), nullable=False),
        sa.Column("referred_user_id", sa.BigInteger(), nullable=False),
        sa.Column("activation_event_key", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["referred_user_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["referrer_user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("referral_event_id"),
    )
    op.create_table(
        "referral_premium_awards",
        sa.Column(
            "award_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("referrer_user_id", sa.BigInteger(), nullable=False),
        sa.Column("milestone", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["referrer_user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("award_id"),
    )
    op.create_table(
        "user_filters",
        sa.Column(
            "filter_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "filters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("filter_id"),
    )
    op.create_table(
        "announcements",
        sa.Column(
            "announcement_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("source_channel_id", sa.Text(), nullable=True),
        sa.Column("source_message_id", sa.Text(), nullable=True),
        sa.Column(
            "source_message_ids",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("parent_announcement_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("canonical_rank", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("source_count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("latest_source_id", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("forward_origin_key", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.Text(), nullable=True),
        sa.Column("price_period", sa.Text(), server_default=sa.text("'monthly'"), nullable=False),
        sa.Column("price_basis", sa.Text(), server_default=sa.text("'total'"), nullable=False),
        sa.Column("price_normalized_monthly", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("rooms", sa.Integer(), nullable=True),
        sa.Column("area_sqm", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("floor", sa.Integer(), nullable=True),
        sa.Column("total_floors", sa.Integer(), nullable=True),
        sa.Column("district", sa.Text(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column(
            "phone_numbers",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("owner_type", sa.Text(), server_default=sa.text("'unknown'"), nullable=False),
        sa.Column("renovation_level", sa.Text(), nullable=True),
        sa.Column(
            "renovation_source", sa.Text(), server_default=sa.text("'unknown'"), nullable=False
        ),
        sa.Column("furniture", sa.Boolean(), nullable=True),
        sa.Column("description", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "audience_tags",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "audience_excluded_tags",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "field_confidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "assumptions",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("is_promoted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("promoted_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["latest_source_id"],
            ["ingestion_sources.source_id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_announcement_id"],
            ["announcements.announcement_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["ingestion_sources.source_id"],
        ),
        sa.PrimaryKeyConstraint("announcement_id"),
    )
    op.create_table(
        "channel_assignments",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("account_key", sa.Text(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_key"],
            ["listener_accounts.account_key"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["ingestion_sources.source_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source_suggestions",
        sa.Column(
            "suggestion_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("source_identifier", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("admin_note", sa.Text(), nullable=True),
        sa.Column(
            "source_type", sa.Text(), server_default=sa.text("'telegram_channel'"), nullable=False
        ),
        sa.Column("reward_granted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["ingestion_sources.source_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("suggestion_id"),
    )
    op.create_table(
        "announcement_media",
        sa.Column("media_id", sa.Text(), nullable=False),
        sa.Column("announcement_id", sa.UUID(), nullable=False),
        sa.Column("storage_url", sa.Text(), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("phash", sa.Text(), nullable=True),
        sa.Column("content_sha256", sa.Text(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["announcement_id"],
            ["announcements.announcement_id"],
        ),
        sa.PrimaryKeyConstraint("media_id"),
    )
    op.create_table(
        "dedup_decisions",
        sa.Column(
            "decision_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("announcement_id", sa.UUID(), nullable=False),
        sa.Column("candidate_announcement_id", sa.UUID(), nullable=True),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("threshold", sa.Integer(), nullable=False),
        sa.Column("config_version", sa.Text(), nullable=False),
        sa.Column(
            "score_breakdown",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["announcement_id"],
            ["announcements.announcement_id"],
        ),
        sa.ForeignKeyConstraint(
            ["candidate_announcement_id"],
            ["announcements.announcement_id"],
        ),
        sa.PrimaryKeyConstraint("decision_id"),
    )
    op.create_table(
        "manual_review_items",
        sa.Column(
            "review_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("announcement_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("related_candidate_id", sa.UUID(), nullable=True),
        sa.Column(
            "score_breakdown",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["announcement_id"],
            ["announcements.announcement_id"],
        ),
        sa.ForeignKeyConstraint(
            ["related_candidate_id"],
            ["announcements.announcement_id"],
        ),
        sa.PrimaryKeyConstraint("review_id"),
    )
    op.create_table(
        "notifications",
        sa.Column(
            "notification_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("announcement_id", sa.UUID(), nullable=False),
        sa.Column("filter_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("priority", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("telegram_message_id", sa.Text(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["announcement_id"],
            ["announcements.announcement_id"],
        ),
        sa.ForeignKeyConstraint(
            ["filter_id"],
            ["user_filters.filter_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("notification_id"),
    )
    op.create_table(
        "announcement_merge_audit",
        sa.Column(
            "audit_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("parent_announcement_id", sa.UUID(), nullable=False),
        sa.Column("child_announcement_id", sa.UUID(), nullable=False),
        sa.Column("decision_id", sa.UUID(), nullable=True),
        sa.Column("merge_policy", sa.Text(), nullable=False),
        sa.Column(
            "conflicts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["child_announcement_id"],
            ["announcements.announcement_id"],
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["dedup_decisions.decision_id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_announcement_id"],
            ["announcements.announcement_id"],
        ),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_table(
        "notification_delivery_attempts",
        sa.Column(
            "attempt_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("notification_id", sa.UUID(), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("error_type", sa.Text(), nullable=True),
        sa.Column("retryable", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("telegram_message_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.notification_id"],
        ),
        sa.PrimaryKeyConstraint("attempt_id"),
    )
    op.execute(
        sa.text(
            """
        alter table users add constraint uq_users_referral_code unique (referral_code);

        alter table announcements add constraint uq_announcements_idempotency_key unique (idempotency_key);

        alter table announcement_media add constraint uq_announcement_media_object_key unique (object_key);

        alter table processing_jobs add constraint uq_processing_jobs_queue_idempotency unique (queue_name, idempotency_key);

        alter table audience_tag_types add constraint uq_audience_tag_types_tag_key unique (tag_key);

        alter table source_suggestions add constraint uq_source_suggestions_source_identifier unique (source_identifier);

        alter table referral_events add constraint uq_referral_events_referred_user_id unique (referred_user_id);
        alter table referral_events add constraint uq_referral_events_activation_event_key unique (activation_event_key);

        alter table referral_premium_awards add constraint uq_referral_premium_awards_referrer_milestone unique (referrer_user_id, milestone);

        alter table notifications add constraint uq_notifications_user_announcement_filter unique (user_id, announcement_id, filter_id);

        alter table announcement_merge_audit add constraint uq_announcement_merge_audit_child_announcement_id unique (child_announcement_id);

        alter table admin_audit_events add constraint uq_admin_audit_events_idempotency_key unique (idempotency_key);

        alter table content_channel_posts add constraint uq_content_channel_posts_idempotency_key unique (idempotency_key);

        alter table analytics_events add constraint uq_analytics_events_idempotency_key unique (idempotency_key);

        alter table technical_metric_events add constraint uq_technical_metric_events_idempotency_key unique (idempotency_key);

        alter table listener_accounts add constraint ck_listener_accounts_health_status
            check (health_status in ('online', 'reconnecting', 'flood_wait', 'disabled', 'banned'));
        alter table listener_accounts add constraint ck_listener_accounts_flood_wait_count_nonnegative
            check (flood_wait_count >= 0);

        alter table ingestion_sources add constraint ck_ingestion_sources_source_type
            check (source_type in ('telegram_channel', 'telegram_group', 'website'));
        alter table ingestion_sources add constraint ck_ingestion_sources_status
            check (status in ('active', 'disabled', 'degraded', 'deleted'));
        alter table ingestion_sources add constraint ck_ingestion_sources_failure_count_nonnegative
            check (failure_count >= 0);
        alter table ingestion_sources add constraint ck_ingestion_sources_average_response_ms_nonnegative
            check (average_response_ms is null or average_response_ms >= 0);

        alter table channel_assignments add constraint ck_channel_assignments_reason
            check (reason in ('initial', 'rebalance', 'failover', 'source_disabled'));
        alter table channel_assignment_audit add constraint ck_channel_assignment_audit_reason
            check (reason in ('initial', 'rebalance', 'failover', 'source_disabled'));

        create unique index uq_channel_assignments_one_active_source
            on channel_assignments(source_id)
            where active;
        create index ix_channel_assignments_active_account
            on channel_assignments(account_key)
            where active;

        alter table users add constraint ck_users_active_referral_count_nonnegative
            check (active_referral_count >= 0);
        alter table users add constraint ck_users_status
            check (status in ('active', 'disabled', 'deleted'));

        alter table announcements add constraint ck_announcements_status
            check (status in ('active', 'archived', 'manual_review', 'deleted'));
        alter table announcements add constraint ck_announcements_source_count_min
            check (source_count >= 1);
        alter table announcements add constraint ck_announcements_price_period
            check (price_period in ('daily', 'monthly', 'one_time'));
        alter table announcements add constraint ck_announcements_price_basis
            check (price_basis in ('total', 'per_person'));
        alter table announcements add constraint ck_announcements_rooms_nonnegative
            check (rooms is null or rooms >= 0);
        alter table announcements add constraint ck_announcements_area_sqm_nonnegative
            check (area_sqm is null or area_sqm >= 0);
        alter table announcements add constraint ck_announcements_owner_type
            check (owner_type in ('owner', 'agent', 'unknown'));
        alter table announcements add constraint ck_announcements_renovation_level
            check (renovation_level is null or renovation_level in ('none', 'basic', 'good', 'euro', 'luxury'));
        alter table announcements add constraint ck_announcements_renovation_source
            check (renovation_source in ('vision', 'text', 'unknown'));
        alter table announcements add constraint ck_announcements_confidence_range
            check (confidence is null or (confidence >= 0 and confidence <= 1));
        alter table announcements add constraint ck_announcements_parent_not_self
            check (parent_announcement_id is null or parent_announcement_id <> announcement_id);

        alter table announcement_media add constraint ck_announcement_media_size_bytes_nonnegative
            check (size_bytes >= 0);

        alter table notifications add constraint ck_notifications_status
            check (status in ('pending', 'sent', 'failed', 'suppressed'));
        alter table notifications add constraint ck_notifications_priority_nonnegative
            check (priority >= 0);
        alter table notifications add constraint ck_notifications_attempts_nonnegative
            check (attempts >= 0);

        alter table notification_delivery_attempts add constraint ck_notification_delivery_attempts_attempt_no_nonnegative
            check (attempt_no >= 0);
        alter table notification_delivery_attempts add constraint ck_notification_delivery_attempts_result
            check (result in ('sending', 'sent', 'retryable_failure', 'permanent_failure', 'rate_limited', 'skipped'));

        alter table parsing_logs add constraint ck_parsing_logs_status
            check (status in ('succeeded', 'manual_review', 'failed'));

        alter table processing_jobs add constraint ck_processing_jobs_status
            check (status in ('pending', 'processing', 'succeeded', 'failed', 'dead_letter'));
        alter table processing_jobs add constraint ck_processing_jobs_attempts_nonnegative
            check (attempts >= 0);

        alter table audience_tag_types add constraint ck_audience_tag_types_status
            check (status in ('approved', 'pending', 'rejected'));
        alter table audience_tag_types add constraint ck_audience_tag_types_usage_count_nonnegative
            check (usage_count >= 0);

        alter table source_suggestions add constraint ck_source_suggestions_status
            check (status in ('pending', 'approved', 'rejected'));
        alter table source_suggestions add constraint ck_source_suggestions_source_type
            check (source_type in ('telegram_channel', 'telegram_group'));

        alter table referral_events add constraint ck_referral_events_status
            check (status in ('pending', 'active', 'rejected'));
        alter table referral_premium_awards add constraint ck_referral_premium_awards_milestone_positive
            check (milestone > 0);

        alter table dedup_decisions add constraint ck_dedup_decisions_decision
            check (decision in ('exact_duplicate', 'high_confidence_duplicate', 'possible_duplicate', 'new'));
        alter table dedup_decisions add constraint ck_dedup_decisions_score_nonnegative
            check (score >= 0);
        alter table dedup_decisions add constraint ck_dedup_decisions_threshold_nonnegative
            check (threshold >= 0);

        alter table manual_review_items add constraint ck_manual_review_items_reason
            check (reason in ('possible_duplicate', 'low_confidence', 'business_quality'));
        alter table manual_review_items add constraint ck_manual_review_items_status
            check (status in ('pending', 'approved', 'rejected', 'merged'));

        alter table content_channel_posts add constraint ck_content_channel_posts_post_kind
            check (post_kind in ('daily_stats', 'top_offer', 'district_stats', 'transparency_report'));
        alter table content_channel_posts add constraint ck_content_channel_posts_status
            check (status in ('drafted', 'published', 'dry_run', 'failed'));

        alter table analytics_events add constraint ck_analytics_events_event_name
            check (
                event_name in (
                    'user_registered',
                    'search_completed',
                    'saved_filter_created',
                    'referral_accepted',
                    'referral_activated',
                    'notification_sent',
                    'notification_delivery_failed',
                    'notification_action_open',
                    'notification_action_search',
                    'notification_action_read'
                )
            );

        alter table technical_metric_events add constraint ck_technical_metric_events_metric_name
            check (
                metric_name in (
                    'queue_delay_ms',
                    'ai_fallback_attempt',
                    'ai_validation_failure',
                    'dedup_decision',
                    'notification_retry',
                    'notification_error',
                    'listener_health'
                )
            );

        create unique index uq_announcements_one_parent_per_source_message
            on announcements(source_id, source_channel_id, source_message_id)
            where status <> 'deleted';
        create index ix_announcements_user_search_canonical
            on announcements(status, created_at desc)
            where parent_announcement_id is null and status = 'active';
        create index ix_announcements_parent
            on announcements(parent_announcement_id)
            where parent_announcement_id is not null;
        create index ix_announcements_dedup_candidates
            on announcements(district, rooms, occurred_at desc)
            where parent_announcement_id is null and status = 'active';
        create index ix_announcements_price_search
            on announcements(price_period, price_basis, price_normalized_monthly)
            where parent_announcement_id is null and status = 'active';
        create index ix_announcements_audience_tags_gin
            on announcements using gin(audience_tags);
        create index ix_announcements_sprint4_search_filters
            on announcements(district, rooms, renovation_level, created_at desc)
            where parent_announcement_id is null
              and status = 'active'
              and price_period in ('daily', 'monthly');
        create index ix_announcements_audience_excluded_tags_gin
            on announcements using gin(audience_excluded_tags);
        create index ix_announcements_latest_source
            on announcements(latest_source_id)
            where latest_source_id is not null;

        create index ix_announcement_media_announcement
            on announcement_media(announcement_id);
        create index ix_announcement_media_phash
            on announcement_media(phash)
            where phash is not null;

        create index ix_user_filters_user_enabled
            on user_filters(user_id)
            where enabled;
        create index ix_user_filters_user_created
            on user_filters(user_id, created_at desc);
        create index ix_user_filters_matching_enabled
            on user_filters(enabled, updated_at desc);

        create index ix_processing_jobs_ready
            on processing_jobs(queue_name, status, available_at);
        create index ix_dedup_decisions_announcement
            on dedup_decisions(announcement_id, created_at desc);
        create index ix_manual_review_items_pending
            on manual_review_items(created_at)
            where status = 'pending';

        create index ix_ingestion_sources_active
            on ingestion_sources(source_type, status)
            where enabled and status = 'active';
        create index ix_ingestion_sources_listener_account
            on ingestion_sources(listener_account_key)
            where listener_account_key is not null;

        create index ix_notifications_user_status_created
            on notifications(user_id, status, created_at desc);
        create index ix_notifications_pending_priority_created
            on notifications(priority desc, created_at)
            where status = 'pending';
        create index ix_notifications_ready_delivery
            on notifications(status, next_attempt_at, priority desc, created_at asc)
            where status = 'pending';
        create index ix_notification_delivery_attempts_notification
            on notification_delivery_attempts(notification_id, created_at desc);

        create index ix_referral_events_referrer_status
            on referral_events(referrer_user_id, status);
        create index ix_referral_events_referred_status
            on referral_events(referred_user_id, status);
        create index ix_referral_audit_events_user_created
            on referral_audit_events(user_id, created_at desc);

        create index ix_admin_audit_events_entity_created
            on admin_audit_events(entity_type, entity_id, created_at desc);
        create index ix_content_channel_posts_created
            on content_channel_posts(created_at desc);
        create index ix_content_channel_posts_retry
            on content_channel_posts(next_attempt_at)
            where status = 'failed';

        create index ix_audience_tag_types_pending
            on audience_tag_types(created_at)
            where status = 'pending';
        create index ix_audience_tag_types_approved_usage
            on audience_tag_types(usage_count desc, tag_key)
            where status = 'approved';
        create index ix_source_suggestions_status_created
            on source_suggestions(status, created_at);
        create index ix_source_suggestions_pending
            on source_suggestions(created_at)
            where status = 'pending';

        create index ix_analytics_events_name_time
            on analytics_events(event_name, occurred_at);
        create index ix_analytics_events_user_time
            on analytics_events(user_id, occurred_at)
            where user_id is not null;
        create index ix_analytics_events_subject_time
            on analytics_events(subject_id, occurred_at)
            where subject_id is not null;

        create index ix_technical_metric_events_name_time
            on technical_metric_events(metric_name, occurred_at);
        create index ix_technical_metric_events_component_time
            on technical_metric_events(component, occurred_at)
            where component is not null;
        create index ix_technical_metric_events_subject_time
            on technical_metric_events(subject_id, occurred_at)
            where subject_id is not null;

        insert into audience_tag_types(tag_key, display_name_uz, status)
        values
            ('family', 'Oila', 'approved'),
            ('family_with_children', 'Bolali oila', 'approved'),
            ('students', 'Talabalar', 'approved'),
            ('single_male', 'Yolg''iz erkak', 'approved'),
            ('single_female', 'Yolg''iz ayol', 'approved'),
            ('group_of_girls', 'Qizlar guruhi', 'approved'),
            ('group_of_boys', 'Yigitlar guruhi', 'approved'),
            ('foreigners', 'Chet elliklar', 'approved')
        on conflict (tag_key) do nothing;
        """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_delivery_attempts")
    op.drop_table("announcement_merge_audit")
    op.drop_table("notifications")
    op.drop_table("manual_review_items")
    op.drop_table("dedup_decisions")
    op.drop_table("announcement_media")
    op.drop_table("source_suggestions")
    op.drop_table("channel_assignments")
    op.drop_table("announcements")
    op.drop_table("user_filters")
    op.drop_table("referral_premium_awards")
    op.drop_table("referral_events")
    op.drop_table("referral_audit_events")
    op.drop_table("ingestion_sources")
    op.drop_table("users")
    op.drop_table("technical_metric_events")
    op.drop_table("processing_jobs")
    op.drop_table("parsing_logs")
    op.drop_table("listener_accounts")
    op.drop_table("feature_flag_states")
    op.drop_index(
        "ix_feature_flag_audit_events_flag_name_occurred_at", table_name="feature_flag_audit_events"
    )
    op.drop_table("feature_flag_audit_events")
    op.drop_table("content_channel_posts")
    op.drop_table("channel_assignment_audit")
    op.drop_table("audience_tag_types")
    op.drop_table("analytics_events")
    op.drop_table("admin_audit_events")
    # ### end Alembic commands ###
